services:
  
  invoiceninja:
    image: tiredofit/invoiceninja
    container_name: invoiceninja
    links:
      - invoiceninja-db
    volumes:
      ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
      #- ${APP_DATA_DIR}/data:/www/html
      ### Or, if you just want to use Stock invoiceninja and hold onto persistent files like cache and session use this, one or the other.
      - ${APP_DATA_DIR}/data:/data
      ### If you want to just keep the original source and add additional modules uncomment this line
      - ${APP_DATA_DIR}/logs/:/www/logs
    environment:
      - CONTAINER_NAME=invoiceninja
      - TIMEZONE=${TZ}
      
      - DB_HOST=invoiceninja-db
      - DB_NAME=invoiceninja
      - DB_USER=invoiceninja
      - DB_PASS=${INVOICENINJA_ADMIN_DB_PASSWORD}

      - SITE_URL=https://${INVOICENINJA_APP_URL}

      - ADMIN_EMAIL=${INVOICENINJA_ADMIN_USER}
      - ADMIN_PASS=${INVOICENINJA_ADMIN_PASSWORD}

      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
    networks:
      - tipi_main_network
      - services
    restart: always

  invoiceninja-db:
    image: tiredofit/mariadb:10.11
    container_name: invoiceninja-db
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
    environment:
      - CONTAINER_NAME=invoiceninja-db
      - TIMEZONE=${TZ}

      - ROOT_PASS=${INVOICENINJA_ADMIN_DB_ROOT_PASSWORD}
      - DB_NAME=invoiceninja
      - DB_USER=invoiceninja
      - DB_PASS=${INVOICENINJA_ADMIN_DB_PASSWORD}

    networks:
      - services
    restart: always

  invoiceninja-db-backup:
    container_name: invoiceninja-db-backup
    image: tiredofit/db-backup:latest
    links:
     - invoiceninja-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=${TZ}
      - CONTAINER_NAME=invoiceninja-db-backup
      - DB01_HOST=invoiceninja-db
      - DB01_TYPE=mariadb
      - DB01_NAME=invoiceninja
      - DB01_USER=invoiceninja
      - DB01_PASS=${INVOICENINJA_ADMIN_DB_PASSWORD}
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  tipi_main_network:
    external: true
  services:
    external: false